name: Build Fantasy Footbot
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
env:
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Github Package Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u ${{ github.repository }} --password-stdin
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag fantasy-footbot:latest --build-arg BOT_TOKEN=${{ secrets.BOT_TOKEN }}
      - name: Tag the Docker image
        run: docker tag fantasy-footbot:latest docker.pkg.github.com/berryscottr/fantasy-footbot/fantasy-footbot:latest
      - name: Push the Docker image
        run: docker push docker.pkg.github.com/berryscottr/fantasy-footbot/fantasy-footbot:latest
      - name: Run the Docker image
        run: docker run docker.pkg.github.com/berryscottr/fantasy-footbot/fantasy-footbot:latest
      - uses: gautamkrishnar/keepalive-workflow@v1
